### ISSUE TITLE
pytroch3d has changed 

### ISSUE THREAD

**Issue by rita-zeng** [yuhaoooo/Deep3DFaceReconstruction-Pytorch#2]
![2020-11-03 17-23-26屏幕截图](https://user-images.githubusercontent.com/32928342/97968228-567c9700-1df9-11eb-890c-6562dc48f499.png)
![2020-11-03 17-24-37屏幕截图](https://user-images.githubusercontent.com/32928342/97968349-7ca23700-1df9-11eb-88c5-40924c4d07b7.png)
how to change the code at this place

**Comment by csyuhao** [comment]
Sorry for the late reply. The version of my Pytorch3d is '0.2.0', and you can try to install this version. I will update the code as soon as possible for matching the up-to-date Pytorch3d.

**Comment by csyuhao** [comment]
Sorry for the late response, because I spend a lot of time to install PyTorch3D 0.3.0 in my PC. Now, the repo has been updated for the latest PyTorch3D.
