### ISSUE TITLE
About the illumination_layer

### ISSUE THREAD

**Issue by hanssssssss** [yuhaoooo/Deep3DFaceReconstruction-Pytorch#3]
Hi !
Thanks for sharing your wonderful work. I could not understand the SH function in the illumination_layer. Colud you please give me more detail about the implement in illumination_layer?
Thanks again.

**Comment by csyuhao** [comment]
You can find all details from [this function](https://github.com/microsoft/Deep3DFaceReconstruction/blob/5b131a3e67597da67409486e20db50007f48427d/face_decoder.py#L221).
