### ISSUE TITLE
关于相机参数的问题

### ISSUE THREAD

**Issue by Wentao795** [yuhaoooo/Deep3DFaceReconstruction-Pytorch#6]
您好，非常感谢你的工程。我有个疑问，这里_need_const函数中camera_pos为什么是10？他表示什么意思？这个参数和相机内参怎么一起作用投影3d关键点到2d平面？有什么相关资料参考吗？期待您的回复~~~

**Comment by csyuhao** [comment]
The camera settings are the same as the original repo ([this link](https://github.com/microsoft/Deep3DFaceReconstruction/blob/1935ea92af72a72c4cf7b8a677a822afd8554b51/face_decoder.py#L285)). You can detailly read this file to seek further information.
